### ISSUE TITLE
monstache docker image cannot connect to elasticsearch

### ISSUE THREAD

**Issue by evasiba-ericsson** [rwynn/monstache#188]
I have set up a docker compose file with Elasticsearch and Kibana, both version 6.2.4. See below:

```
version: "2.1"
services:
  mongodb:
    restart: always
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "${MONGODB_PORT}:27017"
    healthcheck: 
        test: ["CMD-SHELL","echo", "'db.stats().ok' | mongo localhost:27017/test", "--quiet"]
        interval: 30s
        timeout: 10s
        retries: 5        
    networks:
          eiffel_2.0_1:
            aliases:
              - mongodb

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "${ELASTICSEARCH_PORT1}:9200"
      - "${ELASTICSEARCH_PORT2}:9300"
    depends_on:
      - mongodb
    environment:
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
      - discovery.type=single-node
    healthcheck:
      test: "wget -q -O - http://localhost:9200/_cat/health"
      interval: 1s
      timeout: 30s
      retries: 300
    ulimits:
      memlock:
        soft: -1
        hard: -1

    networks:
          eiffel_2.0_1:
            aliases:
              - elasticsearch
              
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:6.2.4
    expose:
      - "8080"
    ports:
      - "${KIBANA_PORT}:8080"
    depends_on:
      - elasticsearch
    environment:
      - SERVER_PORT=8080
      - SERVER_NAME=kibana.example.org
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    networks:
          eiffel_2.0_1:
            aliases:
              - kibana

  monstache:
    restart: always
    image: rwynn/monstache:4.15.1
    expose:
      - "8080"
    ports:
      - "${MONSTACHE_PORT}:8080"
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - MONSTACHE_MONGO_URL=mongodb:27017
      - MONSTACHE_ES_URLS=[ "http://elasticsearch:9200" ]
    links:
      - elasticsearch

    networks:
          eiffel_2.0_1:
            aliases:
              - monstache

networks:
  eiffel_2.0_1:

```
I get from logs of monstache container:
INFO 2019/03/15 09:40:18 Started monstache version 4.15.1
INFO 2019/03/15 09:40:18 Successfully connected to MongoDB version 4.0.5
ERROR 2019/03/15 09:40:33 Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available
INFO 2019/03/15 09:40:33 Shutting down with exit status 1 after panic.

I need a way to run monstache without building my own docker image but only use the  monstache's prebuilt docker images.

BR
Vali
