### ISSUE TITLE
MongoDB address and docker-compose

### ISSUE THREAD

**Issue by thomasd3** [rwynn/monstache#194]
I have a docker-compose file with mongodb, elastic and monstache.

The same server is running totally separate projects which are independently using mongodb. So, in the docker-compose of each project, the mongo instance is named projectname_mongodb

for example:

projecta_mongodb
projectb_mongodb
etc.

the docker-compose starts like this:

 ```
services:

  projecta_mongodb:
     container_name: projecta_mongodb
     image: 'mongo:latest'
     restart: unless-stopped
     command: /scripts/mongo-run.sh
    ...
```

In the monstache config, I put the name in the connection string, so it looks like:

`mongo-url = "mongodb://root-user:xxxx@projecta_mongodb:27017"
`
and... monstache can't connect to it; I get this:

`Unable to connect to MongoDB using URL mongodb://REDACTED@projecta_mongodb:27017: timed out after 15 seconds`

but if the docker-compose mongodb is named 'mongodb', then the connection happens without any problem.

I have tried with other services and they can access the mongo instance when it has a different name, so it looks like the issue is related to monstache, or a bad configuration on my end.

Is it possible that the name is hardcoded somewhere?

**Comment by rwynn** [comment]
I’m pretty sure there is no hard coding except for using localhost if you don’t give a URL. 

Please check out https://github.com/rwynn/monstache-showcase

I know that works and it connects with a user/pass and hostname of mongo-1. 

Are you binding multiple mongo processes to different ports on the same server? Is Monstache in the same docker network as the mongo connected to?  And using the correct port?

**Comment by thomasd3** [comment]
yes, they're able to communicate. In fact, I just found something:

While monstache is reporting:

`Unable to connect to MongoDB using URL mongodb://REDACTED@projecta_mongodb:27017: timed out after 15 seconds
`

Mongo is reporting something else:

```
2019-03-27T23:10:21.278+0000 I NETWORK [listener] connection accepted from 172.18.0.7:37640 #547 (1 connection now open)
2019-03-27T23:10:21.279+0000 I NETWORK [conn547] received client metadata from 172.18.0.7:37640 conn547: { application: { name: "monstache" }, driver: { name: "mgo", version: "globalsign" }, os: { architecture: "amd64", type: "linux" } }
2019-03-27T23:10:21.279+0000 I NETWORK [conn547] end connection 172.18.0.7:37640 (0 connections now open)
2019-03-27T23:10:21.395+0000 W NETWORK [LogicalSessionCacheRefresh] Unable to reach primary for set rs0
```

So Mongo is receiving the connection from Monstache, but for some reason, it gets dropped and Monstache is reporting it as not being able to connect.

**Comment by thomasd3** [comment]
This is the docker-compose:

```
   projecta_mongodb:
     container_name: projecta_mongodb
     image: 'mongo:latest'
     restart: unless-stopped
     command: /scripts/mongo-run.sh
     working_dir: /scripts
     volumes:
       - '/appdata/projecta_data/mongodb:/data/configdb'
       - '/appdata/projecta_data/mongodb:/data/db'
       - './mongodb/scripts:/scripts'
     expose:
       - 27017
     ports:
       - '27017:27017'
     networks:
       - default
     environment:
       MONGO_REPLICA_SET_NAME: rs0
       MONGO_REPLICAS: 'projecta_mongodb:27017'
       MONGO_REPLICA_SET_MEMBERS: '[{''_id'':0,''host'':''projecta_mongodb:27017'',''priority'':1}]'
       MONGO_USER_ROOT_NAME: root-user
       MONGO_USER_ROOT_PASSWORD: xxx
       MONGO_AUTH_SOURCE: admin
       MONGO_BIND_IP: 0.0.0.0
     healthcheck:
       test: '[ -f /data/health.check ] && exit 0 || exit 1'
       interval: 2s
       timeout: 30s
       retries: 300
     labels:
       - "logio=yes"
```

and the line in the toml file:

`mongo-url = "mongodb://root-user:7rL7Upipj29T@projecta_mongodb:27017"
`
