### ISSUE TITLE
 Error tailing oplog entries: Can't use 'local' database through mongos

### ISSUE THREAD

**Issue by lolgolflol** [rwynn/monstache#207]
INFO 2019/04/18 06:23:43 Started monstache version 4.16.1
INFO 2019/04/18 06:23:43 Successfully connected to MongoDB version 4.0.9
INFO 2019/04/18 06:23:43 Successfully connected to Elasticsearch version 6.3.2
INFO 2019/04/18 06:23:43 Listening for events
ERROR 2019/04/18 06:23:43 Error tailing oplog entries: Can't use 'local' database through mongos

In part 

```toml
# connect to MongoDB using the following URL
mongo-url = "mongodb://localhost:27017"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://localhost:9200"]
```
what mongo-url should I input ( mongos (routing) or mongod as primary shard )? but I try to use the both, I still get the same error.
