### ISSUE TITLE
docker-compose command being ignored

### ISSUE THREAD

**Issue by Garito** [rwynn/monstache#278]
Hi!
I have this compose service:
``` yaml
monstache:
    image: rwynn/monstache:4.15.1
    depends_on:
      - es1
      - es2
      - mongo1
      - mongo2
      - mongo3
    environment:
      - MONSTACHE_MONGO_URL=mongodb://${MONSTACHE_MONGO_USER}:${MONSTACHE_MONGO_PASSWORD}@mongo1:27017
      - MONSTACHE_ES_URLS=http://es1:9200
      - MONSTACHE_ES_USER=${ELASTIC_USER}
      - MONSTACHE_ES_PASS=${ELASTIC_PASSWORD}
    networks:
      - mongo
      - es
    command: monstache -resume -replay -verbose
    restart: on-failure
```
but the -resume -replay & -verbose are being ignored

Could you, please, point me how to configure the service to avoid the config file?

Thanks
