### ISSUE TITLE
Can I run monstache with single Mongodb Instance?

### ISSUE THREAD

**Issue by junwu9333** [rwynn/monstache#285]
We have an environment which only has single mongodb instance deployed, and we do not have mongodb replica set, how can i run Monstache to sync data from mongo to Elastic?

**Comment by rwynn** [comment]
@junwu9333 first option would be to convert your standalone to a single node replica set using the following:

https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/

If, for some reason, you don't want any replica set then you would need to run monstache with the following settings:

```toml
disable-change-events = true
direct-read-namespaces = ["db1.col1", "db1.col2", "db2.col1"]
exit-after-direct-reads = true
```

In that configuration, you would only be able to do full sync of the named collections and you would not be able to resume from previous points in time.   You could run this process periodically, but it would do a full sync each time.
