### ISSUE TITLE
More than 150 connections a minute to Mongo 

### ISSUE THREAD

**Issue by ywadi** [rwynn/monstache#312]
I am experiencing a very odd behavior where monstache is opening around 150 connections a minute. Can not figure out why at all, I can see that in the mongo logs on Atlas.

**Comment by rwynn** [comment]
@ywadi Can you try the following settings with the latest monstache `v6.4.1` to ensure you are using latest and greatest go driver from MongoDB.  Monstache sets application name of `monstache` so all activity from the tool should have that appName label in the logs.  

```toml
# settings to minimize connections

# open one change stream for the whole deployment
change-stream-namespaces = [ "" ]

# disable splitting collections.  read collections with one cursor only
direct-read-split-max = -1

# read only one collection at a time
direct-read-concur = 1

# wait 20s each query instead of MongoDB default 1s for change events.  
[gtm-settings]
max-await-time = "20s"
```
