### ISSUE TITLE
Unable to enable cluster mode: (NotMaster) not master

### ISSUE THREAD

**Issue by gate3** [rwynn/monstache#327]
I keep encountering this error when trying to start cluster mode. My config.toml has the cluster-name config 

```
# enable clustering mode
cluster-name = 'HA'
```

I am using docker and starting two different containers

```
version: '3.4'
services:
    monstache1:
        image: rwynn/monstache:latest
        command:
            -worker worker1 -f /config.toml && -worker worker2 -f /config.toml && -worker worker3 -f /config.toml
        container_name: monstache1
        restart: on-failure
        volumes:
            - ./config.toml:/config.toml
        network_mode: "host"
monstache2:
        image: rwynn/monstache:latest
        command:
            -worker worker1 -f /config.toml && -worker worker2 -f /config.toml && -worker worker3 -f /config.toml
        container_name: monstache2
        restart: on-failure
        volumes:
            - ./config.toml:/config.toml
        network_mode: "host"
```

I am also getting an error for the http server. Unable to serve http at address :8081: listen tcp: address 8081: missing port in address

**Comment by rwynn** [comment]
I think you need to specify the `http-server-addr` like this...

```toml
# the default value for this is :8080
http-server-addr = ":8081"
```
where part before `:`, if supplied, is hostname, defaults to `localhost`. 

Your command can be as simple as...

```
command:
           -f /config.toml
```

The pair of processes will join a cluster `HA` and only 1 will sync while the other will be a hot standby.  

I don't think you need workers, but if you want to configure those you need to start a process for each worker.  

```
monstache -workers a -workers b -workers c -worker a
monstache -workers a -workers b -workers c -worker b
monstache -workers a -workers b -workers c -worker c
```
Each process is told about all 3 worker names [a, b, c] and also is assigned one of the three (last arg).

With a config file `config.toml` above would be like 

```toml
workers = ["a", "b", "c"]
```

```
monstache -f config.toml -worker a
monstache -f config.toml -worker b
monstache -f config.toml -worker c
```

**Comment by gate3** [comment]
Thank you for getting back. I made the changes, I stopped using workers and simplified the command as suggested, however, the error persists

```ERROR 2020/01/03 21:16:41 Unable to enable cluster mode: (NotMaster) not master```

New look of my docker-compose file

```
monstache1:
        image: rwynn/monstache:latest
        command:
            -f /config.toml --enable-http-server --http-server-addr=:8081   
        container_name: monstache1
        restart: on-failure
        volumes:
            - ./config.toml:/config.toml
        network_mode: "host"
    monstache2:
        image: rwynn/monstache:latest
        command:
            -f /config.toml        
        container_name: monstache2
        restart: on-failure
        volumes:
            - ./config.toml:/config.toml
        network_mode: "host"
```
I still also have this in my config.toml

```cluster-name = "HA"```
