### ISSUE TITLE
Support for AWS Dynamic Credentials

### ISSUE THREAD

**Issue by kush-patel-hs** [rwynn/monstache#333]
We're currently doing a SPIKE and some research into using Elasticsearch potentially with Monstache. The tool is working great so far locally. We're trying to figure out how we can deploy it. We have self-hosted Mongo with basic auth, but we have an IAM role for elasticsearch. When we use AWS IAM roles they last for 1 hour and then they refresh. So we can't just launch monstache and let it run. Atm we would have to somehow restart monstache every hour.

aws-sdk-go has support for reading from the ~/.aws/credentials file https://github.com/aws/aws-sdk-go/blob/4f042170d30a74a7b1333268a83154c32347f990/aws/credentials/shared_credentials_provider.go#L29 and also expire these credentials and read the file again when they do expire.

It would be great to have similar support in monstache. Both reading from ~/.aws/credentials and dynamically expiring and reading from it again. We could potentially update the `aws-connect` configuration to fallback on ~/.aws/credentials if access-key/secret are missing. Or add in a filename and profile.

**Comment by rwynn** [comment]
Do you have time to submit a PR for monstache for this?  I noticed that shared credentials provider you linked does not actually refresh since after reading the `credentials` file though.  `IsExpired` returns false forever after the file is read.  Is that how you read that code?  It looks like the [endpoints provider](https://github.com/aws/aws-sdk-go/blob/4f042170d30a74a7b1333268a83154c32347f990/aws/credentials/endpointcreds/provider.go) is more along the lines of something that monstache could use in this case?  Specifically, this [one](https://github.com/aws/aws-sdk-go/blob/4f042170d30a74a7b1333268a83154c32347f990/aws/defaults/defaults.go#L122) seems to be able to use the [metadata service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials) to refresh if I'm not mistaken.

**Comment by kush-patel-hs** [comment]
I might have time to work on this if we come up with a plan of attack. You're right I might have read that provider wrong. Hm I'm not sure if that matches our use case. What you're suggesting would use an AWS Service to refresh the token right? 

In our case our service on kubernetes has a sidecar for Vault. And vault assumes an AWS IAM role (which gives creds that last 1 hour), these creds are then written to the ~/.aws/credentials file. Then in an hour Vault will refresh them and write again. So the actual refreshing credentials part is already handled. We just need monstache to be able to keep using the latest variables (i.e if that file changes then use the new creds, not refresh the creds themselves). If that makes sense.

**Comment by rwynn** [comment]
@kush-patel-hs can you please try the [issue-333](https://github.com/rwynn/monstache/tree/issue-333) branch and let me know if that helps?  Switch to that branch and `go install` the binary.  You can configure as follows...

```toml
[aws-connect]
# choose a strategy that looks in environment vars and then ~/.aws/credentials.
strategy = 1
# set the profile to use
profile = "dev-profile" 
# force expire the credentials every 5 minutes forcing a re-read
force-expire = "5m"
# add AWS region 
region = "us-east-1"
```

Strategy `0` is backwards compatible and uses the previous static credentials. Strategy `1` shown above will read the standard AWS environment variables and if empty fall back to the `credentials` file.  Strategy `2` will lookup the credentials via AWS metadata services.

**Comment by kush-patel-hs** [comment]
Hello @rwynn, sorry for the late reply, I'm on vacation!

Your branch is headed in the right direction! 

A few things to iron out.

The duration force expiry (say I set it to 5 min, and our system updates the creds at 6m, then our creds will be wrong for 4m). I could set it to something very low like 15s and I think that would work well for reading env vars, but might be too io intensive for reading file. We could look into using something from here https://github.com/fsnotify to watch the file for changes on top of the force expire. We could also split the env var reading and file reading into two strategies so with env var we can refresh very frequently (10-15s) and with file reading we can watch for changes. 

Thanks for the fast turn around! My teammate is continuing our tech evaluation while I'm on vacation.

**Comment by rwynn** [comment]
@kush-patel-hs updated the branch based on your feedback.  Thanks.

**Comment by rwynn** [comment]
@kush-patel-hs I've merged this code into the `rel6` and `rel5` branches for evaluation now.  You can use a config like this.

```toml
[aws-connect]
# choose a strategy that reads from ~/.aws/credentials.
strategy = 1
# set the AWS credential profile to use if not `default`
profile = "dev-profile" 
# set AWS region 
region = "us-east-1"
# enable file watcher
watch-credentials = true
```
