### ISSUE TITLE
Action/metadata line [1] contains an unknown parameter [parent]

### ISSUE THREAD

**Issue by kimus** [rwynn/monstache#348]
```toml
[[script]]
namespace = "some.Customer"
routing = true
script = """
module.exports = function(doc) {
  var meta = { type: 'customer' };
  var id = doc.userId;
  if (id) {
    meta.parent = id;
    meta.routing = id;
  }
  doc._meta_monstache = meta;
  return _.omit(doc, "userId");
}
"""
```

```
TRACE 2020/02/27 11:41:28 HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [parent]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [parent]"},"status":400}
```

**Comment by rwynn** [comment]
@kimus can you check the [compatibility matrix](https://rwynn.github.io/monstache-site/advanced/#versions) to ensure you are using a version of monstache that will work with your version of Elasticsearch?

If you still have an issue please post your Elasticsearch and monstache versions.  Thanks.

**Comment by kimus** [comment]
```bash
monstache -v
6.5.1
```

```bash
curl localhost:9200
{
  "name" : "elk",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "Z3eWJ8OgSsew4VI0O1RHcQ",
  "version" : {
    "number" : "7.6.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "7f634e9f44834fbc12724506cc1da681b0c3b1e3",
    "build_date" : "2020-02-06T00:09:00.449973Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

```bash
 mongod --version
db version v4.0.13
git version: bda366f0b0e432ca143bc41da54d8732bd8d03c0
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

**Comment by rwynn** [comment]
I think the `parent` field has been deprecated and remove in recent versions of Elasticsearch.  I will need to research the last version that supported it.  Elasticsearch has removed mapping types and now one needs to use a join field to achieve this.  How to do that with monstache is documented [here](https://rwynn.github.io/monstache-site/advanced/#joins).

**Comment by kimus** [comment]
@rwynn What i've done now was...

1. create the index with the parent-child relations:
```bash
curl -XPUT 'localhost:9200/some.user?pretty' -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "properties": {
      "my_join_field": { 
        "type": "join",
        "relations": {
          "user": "customer"
        }
      }
    }
  }
}
'
```

make sure the routing and index for both collections are the same for both collections and added the 'type' (using my_join_field name):

```toml
[[script]]
namespace = "some.User"
routing = true
script = """
module.exports = function(doc) {
  doc._meta_monstache = { routing: doc._id };
  doc.my_join_field = {
    name: 'user'
  }
  return _.omit(doc, "password", "verificationToken");
}
"""

[[script]]
namespace = "some.Customer"
routing = true
script = """
module.exports = function(doc) {
  var meta = { index: 'some.user' };
  doc.my_join_field = {
    name: 'customer'
  }
  var id = doc.userId;
  if (id) {
    meta.routing = id;
    doc.my_join_field.parent = id;
  }
  doc._meta_monstache = meta;
  return _.omit(doc, "userId");
}
"""
```
