### ISSUE TITLE
No synchronisation and no errors in logs. Mongo 4, ES 7, Monstache 6.5.

### ISSUE THREAD

**Issue by aradyuk** [rwynn/monstache#352]
**Describe the bug**
No synchronisation and no errors in logs. Mongo 4, ES 7.4, Monstache 6.5.

Monstache configuration:

```toml
workers = ["worker0", "worker1", "worker2", "worker3"]

mongo-url = "mongodb://mongo4-staging-ourProject-zone:27016/"
elasticsearch-urls = ["*elastic-staging-testing*"]

namespace-regex = '^staging_ourProject\.products$'

direct-read-namespaces = ["ourProject_ourProject.products"]

change-stream-namespaces = ["staging_ourProject.products"]

direct-read-split-max = -1
direct-read-concur = 1

gzip = false
stats = true
index-stats = false
elasticsearch-max-conns = 6
elasticsearch-max-bytes = 103809024 # 99Mb
elasticsearch-retry = true
dropped-collections = false
dropped-databases = false
replay = false
resume = true
resume-write-unsafe = true
resume-name = "staging_ourProject"
namespace-exclude-regex = ''
verbose = false
exit-after-direct-reads = false
prune-invalid-json = true

enable-http-server = true

[[mapping]]
namespace = "staging_ourProject"
index = "staging_ourProject_1"

[gtm-settings]
channel-size = 512
max-await-time = "10s"

[[script]]
script = """
module.exports = function(doc, ns) {
// the doc namespace e.g. test.test is passed as the 2nd arg
return _.pick(doc, "_id", "some_field1", "some_field2");
}
"""
```
<img width="1645" alt="Screen Shot 2020-03-16 at 17 44 50" src="https://user-images.githubusercontent.com/17545075/76770217-9fbaa080-67ae-11ea-891d-f40a75ed16e1.png">
--
mongo logs:
```2020-03-16T13:07:34.808+0000 I  NETWORK  [conn2065] end connection 10.90.6.141:60966 (13 connections now open)
2020-03-16T13:07:34.812+0000 I  NETWORK  [listener] connection accepted from 10.90.6.141:40458 #2071 (14 connections now open)
2020-03-16T13:07:34.812+0000 I  NETWORK  [conn2071] received client metadata from 10.-.-.-:40458 conn2071: { driver: { name: "mongo-go-driver", version: "v1.3.1" }, os: { type: "linux", architecture: "amd64" }, platform: "go1.14", application: { name: "monstache" } }```

**Comment by rwynn** [comment]
Can you try removing these 2 from your config...

```toml
workers = ["worker0", "worker1", "worker2", "worker3"]
namespace-regex = '^staging_ourProject\.products$'
```

Also noticed your `direct-read-namespaces` is different from `change-stream-namespaces`.  Is that correct?

Is the shutting down message coming because you are stopping monstache manually?  It should only shut down by itself when `exit-after-direct-reads` is true.
