### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by tranztec** [rwynn/monstache#355]
We are getting ready to move into production with monstache but have a question about configuration. It appears when we restart the monstache server that it starts to do the entire collection again. Is there an option to make it start from just the changed documents since it last ran?

**Comment by rwynn** [comment]
I recommend having 2 configurations of monstache.  1 for initial full sync and 1 for subsequent runs.  

```toml
# the full sync config will have direct reads and also turn on resume
resume = true
direct-read-namespaces = [ "test.a", "test.b" ]
change-stream-namespaces = [ "test.a", "test.b" ]
exit-after-direct-reads = true
```
After this completes you should have a timestamp saved in your `monstache` database. The next run will use this to resume.  

```toml
# the normal operation config resumes but only reads the change stream
# you can restart monstache with this config and only the new changes will be considered
resume = true
change-stream-namespaces = [ "test.a", "test.b" ]
```
