### ISSUE TITLE
How to use custom config when using run by yours docker file 

### ISSUE THREAD

**Issue by thieuanh1995hn** [rwynn/monstache#357]
How to use custom config when using run by yours docker file

**Comment by rwynn** [comment]
Does the following link answer your question?

https://github.com/rwynn/monstache-showcase/blob/master/docker-compose.sc.yml

```yaml
monstache:
    image: rwynn/monstache:6.4.1
    container_name: c-monstache
    working_dir: /app
    command: -f ./monstache.config.toml
    volumes:
      - ./monstache.config.toml:/app/monstache.config.toml
      - ./plugin/plugin.so:/app/plugin.so
```

You should not need to customize the source code to load a config file using docker.
