### ISSUE TITLE
[BUG] Dropping a database - deletes indices related to different Database

### ISSUE THREAD

**Issue by chandra2037** [rwynn/monstache#359]
Monstache configuration:

```toml
# propogate dropped collections in MongoDB as index deletes in Elasticsearch
dropped-collections = true
# propogate dropped databases in MongoDB as index deletes in Elasticsearch
dropped-databases = true
```
**Software information (please complete the following information):**
 - Operating System:
 - Monstache Version: 6.5.1
 - MongoDB Version: 4.2.3
 - Elasticsearch Version: 7.5.2
 - Kubernetes Version: 1.14.1

**Setup:**

##### MongoDB Collections

```
test
  testcollection1
  testcollection2
test1db
  testcollection11
  testcollection12
test2db
   testcollection21
   testcollection22
```
#####  ElasticSearch Indices
```
test.testcollection1
test.testcollection2
test1db.testcollection11
test1db.testcollection12
test2db.testcollection21
test2db.testcollection22
```

**Case**

Drop `test` database from Mongo

#####  Expectation:
Deletes the following indices from Elasticsearch
```
test.testcollection1
test.testcollection2
```
#####  Actual:
Deleting `test*` indices, basically deletes all above indices.

Can you please advise.

Thank you for your help.
