### ISSUE TITLE
Performance Improvement tips

### ISSUE THREAD

**Issue by chandra2037** [rwynn/monstache#376]
Monstache configuration:

```toml
elasticsearch-max-conns = 10
elasticsearch-max-bytes = 8000000
gzip = true
direct-read-split-max = 9
stats = true
dropped-databases = false
resume = true
resume-strategy = 0
resume-name = "default"
verbose = true
```

**Software information (please complete the following information):**
 - Operating System: Depoying in Kubernetes
 - Monstache Version: 6.5.4
 - MongoDB Version: 4.2.3
 - Elasticsearch Version: 7.6.2

**Additional context**

- Monstache Memory Limits - 3GB
- No HA
- No additional workers
- Mongo has multiple databases, in each database has multiple collections
- Monstache is listening on all Mongo collections

**Test**
Tested Monstache throughput by updating **22K** documents in a single collection. No other activity going on in Mongo during this time.

As soon as the update complete in Mongo, Monstache is taking around 7-9 minutes to completely reflect the changes in Elastic.

I played with below parameters
- elasticsearch-max-conns = 10 or 15 or 10
- elasticsearch-max-bytes  = 3000000 or 5000000 or 8000000 

I am not seeing much change in update completion times. Memory usage is around 75%

**Questions**

1. Throughput I am getting is reasonable?
1. If not, what other config changes that I can make to increase the throughput?

Thank you for any input on this.

**Comment by rwynn** [comment]
Hi @chandra2037 I would suggest turning `verbose` to `false`, the default.  Verbose is reserved for debugging monstache.  It logs a full trace of every request.

Also, you may want to look at https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html to see if there is any there that could help.  From that page as related to monstache... 

* Monstache always uses bulk requests
* Number of workers/threads is controlled by elasticsearch-max-conns setting
* Monstache cannot use auto-generated IDs because it needs to do updates from MongoDB

The other stuff can be done on the Elasticsearch side.

Finally, you may want to experiment and increase channel-size.  That just allows more reading to occur from MongoDB before waiting for Elasticsearch indexing to complete.  It will be buffered in a go channel in memory, so may cause memory to increase.

```toml
[gtm-settings]
channel-size = 1024
```
