### ISSUE TITLE
monstache docker container is indexing all the collections instead of what's in toml

### ISSUE THREAD

**Issue by yunivrsl** [rwynn/monstache#407]
**Describe the bug**
I have a docker-compose.yml that mounts the local volume of config.toml, which only has certain collections to index, but, monstache is indexing every collection with docs.

**To Reproduce**

docker-compose.yml:
version: '3'
   monstache:
       restart: always
       image: rwynn/monstache:latest
       command: -f ./monstache.config.toml &
       volumes:
          - ./monstache.config.toml:/monstache.config.toml
       ports:
          - '5601:5601'
       external_links:
          - mongo1
          - es01

Monstache configuration:

```toml
mongourl = "mongodb://ip-address/?replicaset=rs
elasticsearch-urls=["http://ip-address:9200"]

direct-read-namespaces = ["dev.users", "dev.address"]
change-stream-namespaces = ["dev.users", "dev.address"]
```

**Expected behavior**
monstache should only index "users" and "address" collection

**Software information (please complete the following information):**
 - Operating System: rhel 6/7
 - Monstache Version:  unknown.. someone else uploaded the docker image.. don't know the version
 - MongoDB Version:  4.0.3
 - Elasticsearch Version: 7.6.2
 - Docker Version: 18.09.5

**Additional context**

**Screenshots**
