### ISSUE TITLE
how can I config multi collection in mongodb to one index in elasticsearch?

### ISSUE THREAD

**Issue by zhengdai** [rwynn/monstache#417]
I want to know how to write the config.toml to make multi collection in mongodb mapping to one index in elasticsearch,not just list the mapping, because the collection is named by month.

**Comment by rwynn** [comment]
You can do that with a script (like below) that omits `namespace` or alternatively with a golang plugin.

```toml
[[script]]
script = """
module.exports = function(doc, ns) {
    doc._meta_monstache = { index: "myIndex" };
    return doc;
}
"""

```
