### ISSUE TITLE
Deleted documents in mongoDB are not deleted in Elasticsearch on monstache start full sync

### ISSUE THREAD

**Issue by casparkirsch** [rwynn/monstache#421]
Hi rwynn,

Is this behavior expected from monstache? Do I have any flaws in my configuration or am I missing any config to reach my desired behavior? See details on setup and reproducing steps below.

Thank you very much for monstache and your effort!

### Current behavior

Monstache only syncs create and update events to Elasticsearch on startup. If a document was deleted from mongoDB while monstache was not running, it stays in the Elasticsearch index even after monstache has synced.

### Desired behavior

I would like monstache to sync all changes (including delete actions) on startup that have occured while it was not running.

### Setup

docker-compose.yml

```
version: '3.4'

services:
  db:
    image: mongo:4.0
    hostname: db
    environment:
      - MONGO_INITDB_DATABASE=db
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db
    command: mongod --replSet rs0
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet
    restart: always

  monstache:
    image: rwynn/monstache:6.7.0
    hostname: db-sync
    environment:
      - MONSTACHE_MONGO_URL=mongodb://db
      - MONSTACHE_ES_URLS=http://elasticsearch:9200
      - MONSTACHE_CHANGE_STREAM_NS=db.col1,db.col2
      - MONSTACHE_DIRECT_READ_NS=db.col1,db.col2
      - MONSTACHE_DIRECT_READ_BOUNDED=true
      - MONSTACHE_DIRECT_READ_STATEFUL=true
      - MONSTACHE_RESUME=true
    depends_on:
      - db
      - elasticsearch
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.0
    hostname: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    restart: always
```

### Steps to reproduce

1. Start containers via docker-compose and initiate Replica Set in mongoDB
2. Add three documents to mongoDB db.col1
3. Stop monstache container
4. Delete one document from mongoDB db.col1
5. Rename the other documents in db.col1
6. Start monstache container again
7. Document names are changed in Elasticsearch index but the deleted document is also still there

**Comment by rwynn** [comment]
I think the problem might be that some the options you've defined as env variables are currently only available in the config file or as program arguments.  The example below moves those 3 to arguments.  

```yaml
 monstache:
    image: rwynn/monstache:6.7.0
    hostname: db-sync
    command: -resume -direct-read-bounded -direct-read-stateful
    environment:
      - MONSTACHE_MONGO_URL=mongodb://db
      - MONSTACHE_ES_URLS=http://elasticsearch:9200
      - MONSTACHE_CHANGE_STREAM_NS=db.col1,db.col2
      - MONSTACHE_DIRECT_READ_NS=db.col1,db.col2
    depends_on:
      - db
      - elasticsearch
    restart: always

```
