### ISSUE TITLE
[[relate]] two way relation 

### ISSUE THREAD

**Issue by kbonevska** [rwynn/monstache#429]
Hello there, admirations for the project, amazing work.

We have the following relation mapping in our config, but it seems it is causing an endless loop of updates in the elastic. 
Is it possible to do such relation with [[relate]]? 

direct-read-namespaces = ["authors","articles"]
change-stream-namespaces = ["authors","articles"]
resume-strategy = 1

[[relate]]
namespace = "authors"
with-namespace = "articles"
src-field = "topicID"
match-field = "topicID"
keep-src = true

[[relate]]
namespace = "articles"
with-namespace = "authors"
src-field = "topicID"
match-field = "topicID"
keep-src = true

**Comment by rwynn** [comment]
hi @kbonevska thank you. can you try setting the `max-depth` property of the relate? 

```toml
[[relate]]
namespace = "authors"
with-namespace = "articles"
src-field = "topicID"
match-field = "topicID"
keep-src = true
max-depth = 1

[[relate]]
namespace = "articles"
with-namespace = "authors"
src-field = "topicID"
match-field = "topicID"
keep-src = true
max-depth = 1
```

It probably should be detecting cycles like this.  I will look into that for the next release.
