### ISSUE TITLE
change-stream-namespaces w/ regex

### ISSUE THREAD

**Issue by shurth** [rwynn/monstache#432]
I hate to be _that guy_ asking a question via an issue - but have you considered supporting a regex exclude option for change-stream-namespace (similar to direct-read-dynamic-exclude-regex)? I'd like to use change streams, but I'm dealing with dynamic database names.

**Comment by rwynn** [comment]
If you have MongoDB 4 or greater then you can do something like this...

```toml
# listen to events on the whole cluster
change-stream-namespaces = [ "" ]
# drop any events with namespace matching regex 
namespace-exclude-regex = '^not\.mytempo$'
```
