### ISSUE TITLE
Plugin was built with a different version

### ISSUE THREAD

**Issue by alan0803-kr** [rwynn/monstache#488]
Hi I am trying to build the plugin but getting this error:

```
plugin was built with a different version of package github.com/rwynn/monstache/monstachemap
```

I thought I have configured to use the exact same release version, but wondering why the version is not matching. 
Here are the portion of image and commands I am using.

> I'm using Kubernetes and excluded unrelated parts. You can assume the files are correctly mounted. 

```yaml
# monstache container
image: docker.io/rwynn/monstache:6.7.4
command: ["monstache", "-f", "config,toml", "-mapper-plugin-path", "plugin.so"]
volumeMounts:
   # uses the plugin.so built from below container

# build plugin container
image: docker.io/rwynn/monstache-builder-cache-rel6:1.0.6
command: ["/bin/sh", "-c"]
args:
- |
    git clone --depth 1 --branch v6.7.4 https://github.com/rwynn/monstache.git .
    go install
    go build -buildmode=plugin -ldflags="-s -w" -o plugin.so plugin.go
```

However mounting the `plugin.so` built with the plugin build scripts works fine. 
```sh
git clone --depth 1 --branch v6.7.4 https://github.com/rwynn/monstache.git .
cd monstache/docker/plugin
# copy plugin.go to this dir
./build_sh
# mount docker_build/plugin.so to "docker.io/rwynn/monstache:6.7.4"
# and monstache runs with no error
```

Any parts am I missing here? Thank you.

**Comment by rwynn** [comment]
Hi @alan0803-kr haven't had a chance to look into your approach too deeply but nothing jumps out.   Have you seen the wiki page? 

https://github.com/rwynn/monstache/wiki/Build-and-run-a-monstache-docker-container-image-with-an-embedded-go-plugin

I think that process should work.  Maybe it can give you some ideas to try.

**Comment by alan0803-kr** [comment]
Thank you for providing the wiki @rwynn 

yeah, we got this working by building the plugin and monstache binary using the same source code. wondering why it didn't work on `docker.io/rwynn/monstache:6.7.4`. Possibly some difference in kubernetes environment which isn't sure yet. 

For those of who might run into the same issue in kubernetes, here's the gist of it:

```yaml
initContainers:
  - image: rwynn/monstache-builder-cache-rel6:1.0.6
    command
     1. git clone specific version you want to use
     2. make release
     3. build plugin
     4. copy these binary to volume
     
containers:
  - image: rwynn/monstache-alpine:3.12.1
    command
     1. run monstache binary with plugin built from initContainers
    volumeMounts:
     - mount config file
     - mount binary built from initContainers
```

**Comment by alan0803-kr** [comment]
Thank you for providing the wiki @rwynn 

yeah, we got this working by building the plugin and monstache binary using the same source code. wondering why it didn't work on `docker.io/rwynn/monstache:6.7.4`. Possibly some difference in kubernetes environment which isn't sure yet. 

For those of who might run into the same issue in kubernetes, here's the gist of it:

```yaml
initContainers:
  - image: rwynn/monstache-builder-cache-rel6:1.0.6
    command
     1. git clone specific version you want to use
     2. make release
     3. build plugin
     4. copy these binary to volume
     
containers:
  - image: rwynn/monstache-alpine:3.12.1
    command
     1. run monstache binary with plugin built from initContainers
    volumeMounts:
     - mount config file
     - mount binary built from initContainers
```
