### ISSUE TITLE
Health Check page is not available in Monstache

### ISSUE THREAD

**Issue by pcinnusamy** [rwynn/monstache#489]
Hi Rwynn,

We found  that Monstache doesn’t come with healthcheck page by default, Can you please suggest how to implement this ?

Is anyone already developed using golang or some other language  ?

**Comment by rwynn** [comment]
Hi @pcinnusamy ,

Some observability [features](https://rwynn.github.io/monstache-site/advanced/#http-server) in monstache...

```toml
# this sends stats to Elasticsearch that you can create Kibana dashboards for
stats = true
index-stats = true
# this starts a web server that exposes some endpoints
enable-http-server = true
http-server-addr = ":8080"
```
