### ISSUE TITLE
v6  not support  according to the rules , directy copy  collections from MongoDB to Elasticsearch

### ISSUE THREAD

**Issue by rentiansheng** [rwynn/monstache#490]
namespace-regex start monstache not  to directly copy collections from MongoDB to Elasticsearch

**Comment by rwynn** [comment]
hi @rentiansheng only `direct-read-namespaces` initiates the copy of collections. `namespace-regex` is only a filter on the event (create/update/delete) stream.

**Comment by rentiansheng** [comment]
> hi @rentiansheng only `direct-read-namespaces` initiates the copy of collections. `namespace-regex` is only a filter on the event (create/update/delete) stream.


hi, after I split the collection again, I need to synchronize the data to es according to the collection prefix. I originally configured the direct-read-dynamic-exclude-regex rule of the project, but the golang regex does not support it?!, to achieve this function Need to write all the unnecessary tables to the direct-read-dynamic-exclude-regex configuration, and then need to modify the collection every time, it is prone to problems? What should I do now? Can it only be achieved with plugin?

**Comment by rwynn** [comment]
I think the only option is to use something like this...

```toml
# keep track of what has been copied
direct-read-stateful = true
# query for all collections instead of enumerating each one to copy
direct-read-namespaces = [ "" ]
# a regular expression matched against db.collection.  If there is a match then exclude it.
direct-read-dynamic-exclude-regex = '^ignore'
```

Or write a script to dynamically generate environment variable like this before running monstache.  

```
export MONSTACHE_DIRECT_READ_NS="db.colA,db.colB,db.colC"
```
