### ISSUE TITLE
failed to write: context canceled - Error

### ISSUE THREAD

**Issue by pcinnusamy** [rwynn/monstache#503]
Hi @rwynn ,

I can see the below error got for sometimes when direct read is in progress and final message got that the direct read got succeeded. Could you please check and confirm what needs to be done on this .

ERROR 2021/04/14 06:49:49 Error performing direct read of collection  scb.loan: connection(host:27017[-10]) failed to write: context canceled
 
April 14, 2021 14:49:49.112
INFO 2021/04/14 06:49:49 Direct reads completed

**Comment by rwynn** [comment]
If you having problems with direct reads (this might be a timeout) you can try to scale back the concurrency to see if that helps.  

```toml
direct-read-bounded = true
direct-read-concur= 1
direct-read-no-timeout = true
direct-read-split-max = -1
```
