### ISSUE TITLE
Help: [relate]/Views not working as expected

### ISSUE THREAD

**Issue by adiliqbl** [rwynn/monstache#505]
Hi, I am trying to implement view replication with relate feature. But direct reads is still reading from collection instead of the view. Whereas change events from both Product and User collections doesn't seem to trigger an event.

I'm handling the mapping inside go plugin because of different indices based on conditions. `input.Collection` is always `Product` (collection, along with the data) instead of `ProductView` on direct reads. Thanks for help in advance :)

**Environment**
go version: go1.15.5 linux/amd64
monstache: v6.7.1
mongodb 4.4.5
elasticsearch 7.10.2

**config.toml**
```toml
direct-read-namespaces = ["db.ProductView"]
routing-namespaces = ["", "db.ProductView"]
change-stream-namespaces = ["db.Product", "db.User"]
delete-index-pattern = "new_*,product*"

[[relate]]
namespace = "db.Product"
with-namespace = "db.ProductView"
keep-src = false

[[relate]]
namespace = "db.User"
with-namespace = "db.Product"
src-field = "_id"
match-field = 'user\uff0e_id'
keep-src = false
```

**Comment by rwynn** [comment]
Hi @adiliqbl did you find a solution to this problem?  If not, if you can post an example of your plugin code I can try to help.  I don't see any problems immediately in the config you posted.  

As an aside, with recent versions of monstache you can configure the 2nd relate like this.

```toml
[[relate]]
namespace = "db.User"
with-namespace = "db.Product"
src-field = "_id"
match-field = 'user._id'
keep-src = false
dot-notation = true
```
