### ISSUE TITLE
Monstache stalling while indexing large collection holding 700K documents

### ISSUE THREAD

**Issue by jayminkapish** [rwynn/monstache#509]
Monstache has been working really well for us in the staging environment past couple of weeks. It gave us a lot of excitement syncing 23K documents from staging database to staging elasticsearch cluster very quickly (< 10m). We then moved the deployment to production 3 days ago with the same configuration toml file as staging except the production collection size is very big. COLLECTION SIZE:  4.97GB and TOTAL DOCUMENTS:  713458

We are looking to sync entire mongo collection onto the elasticsearch cluster and then tail the oplog.

```toml
verbose = false

enable-http-server = true

namespace-regex = "^db.collection$"

resume = true

stats = true

stats-duration = "30s"

debug = false

elasticsearch-retry = true

elasticsearch-max-docs = 50

elasticsearch-client-timeout = 60000

[[mapping]]
namespace = "db.collection"
index = "db"

[[script]]
namespace = "db.collection"
script = """
module.exports = function(doc, ns, updateDesc) {
    // the doc namespace e.g. test.test is passed as the 2nd arg
    // if available, an object containing the update description is passed as the 3rd arg
    return _.omit(doc, "raw", "name", "email", "_uid");
}
"""
```

And we have the following env vars:

```
{
  "monstache-direct-read-ns": "db.collection",
  "monstache-es-urls": "es_connection_url",
  "monstache-mongo-url": "mongo_connection_url"
}
```

Monstache kicked off sync at higher rate but after just a few hours it seems to be stalling and only indexing 2-5 documents a minute. It logged `Direct reads completed` after about 6h.

and stats timer logs stats

```
STATS 2021/05/11 01:59:52 {"Flushed":53745,"Committed":10426,"Indexed":230959,"Created":0,"Updated":0,"Deleted":1,"Succeeded":229042,"Failed":1918,"Workers":[{"Queued":0,"LastDuration":52000000},{"Queued":0,"LastDuration":8000000},{"Queued":0,"LastDuration":7000000},{"Queued":0,"LastDuration":12000000}]}
```

Monstache also logged the following error about 800 times in the first few hours of production sync kick off:

```
ERROR 2021/05/08 03:54:28 Bulk response item: {"_index":"attribute","_type":"_doc","_id":"5fd98c7287761f000163fe59","status":500,"error":{"type":"mapper_exception","reason":"timed out while waiting for a dynamic mapping update"}}
```

We've allocated 2 CPUs and 4gb memory to the monstache and it is hardly using 2% of it at the moment.

Can you tell us looking at the config what can we do to speed up the sync?

Thanks in advance.
