### ISSUE TITLE
Where is the config file in docker image?

### ISSUE THREAD

**Issue by BongBongBang** [rwynn/monstache#536]
I need to replace the config file in my k8s.But I can not find the default config .....
So...

**Comment by abbudao** [comment]
Just mount your configuration in a volume and replace the command to point to your file.
If you've mounted your config to `/etc/config/config.toml`, start it with something like:
```yaml
    spec:
      containers:
      - name: monstache
        image: rwynn/monstache:6.7.5
        command: ["monstache", "-f", "/etc/config/config.toml"]
```
