### ISSUE TITLE
can't make synchronization work with docker-compose

### ISSUE THREAD

**Issue by GiorgiSheklashvili** [rwynn/monstache#566]
Hello,
I was running monstache from cloned repository with this .toml configuration
```
mongo-url = 'REMOVED'
elasticsearch-urls = ["REMOVED:9243"]

elasticsearch-user="REMOVED"
elasticsearch-password="REMOVED"
elasticsearch-max-conns = 5
replay = false
resume = true
enable-oplog = false
resume-name = "es-monstache-demo"
namespace-regex = 'kraken\.productmodels$$'
direct-read-namespaces = ["kraken.productmodels"]
index-as-update = true
verbose = true
exit-after-direct-reads = false

[[mapping]]
namespace = "kraken.productmodels"
index = "monstache_demo"
```

so this was working properly but now I want to run monstache with this configuration on aws so I created docker-compose.yml file. When I'm running docker compose everything is running without errors, but when I'm updating mongodb table, updates are not synchronized with elasticsearch. I opened the logs of docker compose and there were only /_bulk post requests executed. So my question is what do I have wrong in my configuration?

Docker-compose.yml
```
version: '3'
services:
  monstache_container_name:
    image: 'rwynn/monstache:latest'
    container_name: monstache
    working_dir: /monstache
    command: '-f ./config.toml'
    volumes:
      - './monstache:/monstache/'
      - './config.toml:/config.toml'
    ports:
      - '9243:9243'
    restart: always
networks:
  app-network:
    driver: bridge

```

config.toml
```

mongo-url = 'REMOVED'
elasticsearch-urls = ["REMOVED:9243"]

elasticsearch-user="REMOVED"
elasticsearch-password="REMOVED"
elasticsearch-max-conns = 5
replay = false
resume = true
enable-oplog = false
resume-name = "es-kraken"
namespace-regex = 'kraken\.productmodels$$'
direct-read-namespaces = ["kraken.productmodels"]
index-as-update = true
verbose = true
exit-after-direct-reads = false

[[mapping]]
namespace = "kraken.productmodels"
index = "kraken"

[[script]]
namespace = "kraken.productmodels"
path = "./scripts/collection_name.js"
routing = true

[logs]
error = "./logs/error.log" 

```

**Comment by rwynn** [comment]
Can you share a little more detail about  MongoDB in AWS?  What version is it?  Are you using DocumentDB or MongoDB?

Also, do you receive any errors when you add this to your config?

```toml
change-stream-namespaces = ["kraken.productmodels"]
```

**Comment by GiorgiSheklashvili** [comment]
I'm using mongoDB 4.4 version and it is on mongoDB atlas. when creating the cluster I chose dedicated type(becuase serverles didn't create log of past action I think, which monstache needed). The data are added there as expected now.
This is configuration:
![image](https://user-images.githubusercontent.com/9293826/136515108-b90d8e89-f430-429d-8e26-68cdb00a850c.png)
And yes, after adding
`change-stream-namespaces = ["kraken.productmodels"]`
I received this error
![image](https://user-images.githubusercontent.com/9293826/136515788-2f85afe6-d8ce-45f3-ac8d-981219957fd1.png)

**Comment by IlyaShkurenko** [comment]
Seems I have same issue. Collections are not syncing anymore after update. This was working before

**Comment by GiorgiSheklashvili** [comment]
I changed ports: 8080:8080 and command: 'monstache -f ./config.toml' and now it seems to work locally. But still it didn't update elasticsearch on delete of the object in mongo.(update of the fields did synchronize though)

**Comment by rwynn** [comment]
Try adding ...
```toml
delete-index-pattern = "kraken*"
routing-namespaces = ["kraken.productmodels"]
```
Assuming your Elasticsearch index is something like `kraken`
