### ISSUE TITLE
Monstache Stops Syncing After Repeated HTTP 504 Errors

### ISSUE THREAD

**Issue by patrickserrano** [rwynn/monstache#570]
Hi @rwynn

My team is in the process of deploying Monstache to our staging environment and we're noticing some strange behavior that I was hoping you might have some insight on.

We're seeing instances where Monstache is getting HTTP 504 errors over a period of time, and then it just stops syncing data until we've restarted the Monstache processes. We're using Elasticsearch v7.10.1 with Mongo v4.0.12 and Monstache v6.7.5

I'm working with our DevOps team to try and figure out why we're seeing the 504 errors in the first place, but I didn't see anything in the Monstache documentation that would suggest that a string of timeouts like that would kill the processes. But that _seems_ to be the behavior that we're seeing at the moment.

We're deploying Monstache in Kubernetes with 2 pods so that we have high availability with this config:

```toml
direct-read-namespaces = [
    "collection-1",
    "collection-2",
    "collection-3",
    "collection-4"
]

change-stream-namespaces = [
    "collection-1",
    "collection-2",
    "collection-3",
    "collection-4"
]

mapper-plugin-path="/lib/plugin.so"
exit-after-direct-reads = false
direct-read-stateful = true
resume = true
resume-write-unsafe = true
resume-strategy = 0
post-processors = 10
elasticsearch-retry = true
elasticsearch-max-bytes = 16000000
elasticsearch-max-seconds = 10
enable-easy-json = true
gzip = true
enable-http-server = true
http-server-addr = ":8080"
stats = true
index-stats = true
verbose = true
```

Thanks a ton for any help!
