### ISSUE TITLE
elasticsearch-healthcheck-timeout-startup as environment variable docker compose?

### ISSUE THREAD

**Issue by tamis-laan** [rwynn/monstache#581]
I can't set `elasticsearch-healthcheck-timeout-startup¶` as an environment variable using docker compose:

``` yaml
  monstache:
    image: rwynn/monstache
    environment:
      MONSTACHE_MONGO_URL: "mongodb://mongo:${MONGO_PORT}"
      MONSTACHE_ES_URLS: "http://elasticsearch:9200"
      MONSTACHE_CHANGE_STREAM_NS: myindex
      MONSTACHE_ELASTICSEARCH_HEALTHCHECK_TIMEOUT_STARTUP: 200
      ELASTICSEARCH_HEALTHCHECK_TIMEOUT_STARTUP: 200
      # elasticsearch-healthcheck-timeout-startup: 200
      # ELASTICSEARCH_HEALTHCHECK_TIMEOUT: 200
    depends_on:
      - mongo
      - elasticsearch
    restart: always
```
This results in: `Unable to create Elasticsearch client: health check timeout`
