### ISSUE TITLE
Some documents were not updated

### ISSUE THREAD

**Issue by neurovul** [rwynn/monstache#585]
Hello,

We are using Monstache on the project I work on with a custom plugin to index documents from subarrays.
We have an issue on production environment, there is a difference between documents in MongoDB and documents in Elasticsearch. It seems that some documents were not updated because some attributes have the wrong values.

We didn't know what happened but we tried to reproduce the issue on a staging environment. I reproduced successfully by scale down Elasticsearch, some documents were not updated when Elasticsearch was operational again. However I don't know if it is what happend on production.

I am stuck on this issue, do you have some ideas to avoid this issue?

Here is my config.toml:

```toml
elasticsearch-user = "elastic"
elasticsearch-validate-pem-file = false

mapper-plugin-path = "/bin/plugin.so"

elasticsearch-urls = ["xxx"]

direct-read-namespaces = ["xxx", "xxx", "xxx"]

namespace-regex = "xxx"

index-oplog-time = true

resume = true

direct-read-stateful = true

[[mapping]]
namespace = "xxx"
index = "xxx"

[[mapping]]
namespace = "xxx"
index = "xxx"
```
