### ISSUE TITLE
Support realtime resume only when es data missing?

### ISSUE THREAD

**Issue by Genuineh** [rwynn/monstache#590]
Hi! Monstache is a helpfull tool that sync data between mongodb and es.
I think mybe the es data will missing, but I could not find the config that can resume data only when es data missing.
I had set resume true but it didn't work for that.

MongoDb version: 4.2
Deployment Mode:  sharded clusters

Monstache: rel6

my toml:
```toml
mongo-url = "mongodb://192.168.1.69:27017"

elasticsearch-urls = ["http://192.168.1.111:9200"]

change-stream-namespaces = [""]
namespace-regex = '^mongodb159_wave.ctwave$'

gzip = true
stats = true
index-stats = true
elasticsearch-user = ""
elasticsearch-password = ""
elasticsearch-max-conns = 4
dropped-collections = false
dropped-databases = false
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
index-files = false
file-highlighting = false
verbose = true
exit-after-direct-reads = false

mapper-plugin-path = "/app/plugin.so"

[[mapping]]
namespace = "mongodb159_wave.ctwave"
index = "159shwave"
```

I'm not good at English, please be more understanding.
Thanks.
