### ISSUE TITLE
Syncing related data

### ISSUE THREAD

**Issue by lgmf** [rwynn/monstache#606]
I have a doubt here

Is there any way of syncing related data?

For example, I have a collection named assets that has a tags property

The tags are stored in their own collection.

On the asset, we only store the tag ID, but we have a script to embed the tag name also (due to text search purposes) before syncing to elastisearch.

Every time an asset has changed the sync works perfectly but when I rename a tag the sync is not triggered.

Is there a magic way that monstache can handle this situation, or I would have to force an update on my asset?

**Comment by rwynn** [comment]
Does this help?
https://rwynn.github.io/monstache-site/advanced/#mongodb-view-replication

**Comment by rwynn** [comment]
```toml
[[relate]]
namespace = "db.tags"
with-namespace = "db.assets"
src-field = "_id" # the field in tags that is used in db.assets.tags
match-field = "tags" # the field in assets. e.g. where db.assets.tags = db.tags._id
keep-src = false # set to true if you also want to index db.tags.  in this case only re-index assets.
```
