### ISSUE TITLE
flag provided but not defined

### ISSUE THREAD

**Issue by tamis-laan** [rwynn/monstache#627]
I'm using docker compose to connect elasticsearch and mongodb using monstache. I'm using a couple of flags but no matter what I do I get `flag provided but not defined` error back from monstache.

``` yml
  monstache:
    image: rwynn/monstache:rel6
    environment:
      MONSTACHE_MONGO_URL: ${MONGO_URL}
      MONSTACHE_ES_URLS: "http://elastic:9200"
      MONSTACHE_CHANGE_STREAM_NS: myns
      MONSTACHE_DIRECT_READ_NS: myns
    command:
      - -replay true
      - -resume true
      - -elasticsearch-healthcheck-timeout-startup 200
    depends_on:
      - mongo
      - elastic
    restart: always
    deploy:
      resources:
        limits:
          memory: 0.1G
```

output:
```
compose-monstache-1  | flag provided but not defined: -replay true
compose-monstache-1  | Usage of /bin/monstache:
compose-monstache-1  |   -change-stream-namespace value
compose-monstache-1  |     	A list of change stream namespaces
compose-monstache-1  |   -cluster-name string
compose-monstache-1  |     	Name of the monstache process cluster
...
compose-monstache-1  |   -replay
compose-monstache-1  |     	True to replay all events from the oplog and index them in elasticsearch
...
compose-monstache-1 exited with code 2
```

**Comment by rwynn** [comment]
monstache uses the [flag](https://pkg.go.dev/flag) package.

```
-flag
-flag=x
-flag x  // non-boolean flags only
```

**Comment by tamis-laan** [comment]
@rwynn 
Can this be in the docs?

**Comment by fengjihu** [comment]
May be, you can try:
```yaml
  monstache:
    image: rwynn/monstache:rel6
    environment:
      MONSTACHE_MONGO_URL: ${MONGO_URL}
      MONSTACHE_ES_URLS: "http://elastic:9200"
      MONSTACHE_CHANGE_STREAM_NS: myns
      MONSTACHE_DIRECT_READ_NS: myns
    command:
      - -replay=true
      - -resume=true
      - -elasticsearch-healthcheck-timeout-startup=200
    depends_on:
      - mongo
      - elastic
    restart: always
    deploy:
      resources:
        limits:
          memory: 0.1G
```
