### ISSUE TITLE
How to monitor Monstache?

### ISSUE THREAD

**Issue by jpgklassen** [rwynn/monstache#632]
What is the best way to monitor Monstache so that we know the moment it stops working? We ran into an issue recently where Monstache filled up the Elasticsearch index with so many logs, Elasticsearch shards were maxed out and Monstache could no longer insert documents into the Elasticsearch index. It took us a long time to realize it wasn't working.

**Comment by rwynn** [comment]
Maybe you can monitor via:

```toml
stats=true
# optionally
enable-http-server=true
http-server-addr='localhost:8080'
```

This will log the number of indexing errors plus other stuff to standard out periodically and also make those same stats available via GET http://localhost:8080/stats or whatever host / port you configure.
