### ISSUE TITLE
Is is possible to do a full collection sync?

### ISSUE THREAD

**Issue by alex-oleshkevich** [rwynn/monstache#67]
I am migrating from mongo-connector and this option is important to me

**Comment by rwynn** [comment]
yes, use `direct-read-namespaces` option.  

https://rwynn.github.io/monstache-site/config/#direct-read-namespaces

either in toml file as 

```
direct-read-namespaces = ["db.col", "db2.col2"]
```

or on command line as 

```
monstache -direct-read-namespace db.col -direct-read-namespace db2.col2

**Comment by alex-oleshkevich** [comment]
well, when I run it, the program uses 1.5Gb of RAM to sync 2.2M documents. i think there is a memory leak, as the memory is not freed after the operation completed

**Comment by rwynn** [comment]
Just using default settings? Do you have any custom config?

**Comment by alex-oleshkevich** [comment]
almost defaults.
command is: 
```bash
monstache -f /etc/config.toml --direct-read-namespace autobot.advert --stats -exit-after-direct-reads
```

config:
```toml
mongo-url = "mongodb:27017"
elasticsearch-urls = ["http://elasticsearch:9200"]

[[mapping]]
namespace = "index.type"
index = "index"
type = "type"
```

![image](https://user-images.githubusercontent.com/635848/39678797-e27145b2-519b-11e8-9f3a-808d9a93963b.png)

ps aux | grep monst
`root     23189 74.2 16.0 1444484 1287092 pts/0 Ssl+ 01:57   8:35 monstache -f /etc/config.toml --direct-read-namespace autobot.advert --stats -exit-after-direct-reads`
