### ISSUE TITLE
[[relate]] is not embedding the child document data in the parent document always

### ISSUE THREAD

**Issue by KarthikRaju391** [rwynn/monstache#740]
I have followed the MongoDB View Replication setup which is described in the Advanced section of the documentation (https://rwynn.github.io/monstache-site/advanced/#mongodb-view-replication)

But I needed certain transformations applied for each document, so I made the following changes to the config file and the script files.

### Config:
```toml
mongo-url = "<mongodb-url>"
elasticsearch-urls = [
   "<es-url>"
]

direct-read-namespaces = [
    "media.videoview",
]

change-stream-namespaces = [
    "media.medias",
    "media.videos",
] 

elasticsearch-max-conns = 12
elasticsearch-max-bytes = 8000000
gzip = true
direct-read-split-max = 9
resume = true
index-as-update = true
# direct-read-no-timeout = true
resume-strategy = 0
# direct-read-stateful = true
elasticsearch-retry = true
fail-fast = false
stats = false
disable-change-events = false
enable-patches = true
elasticsearch-validate-pem-file = false
verbose = true
index-oplog-time = true
resume-name = "discovery.media_videos"
oplog-date-field-format = "2006-01-02T15:04:05.999Z"

[gtm-settings]
buffer-size = 128
channel-size = 512
buffer-duration = "75ms"

[[mapping]]
namespace = "media.medias" # map change events on the thing collection to the things index
index = "media.medias"

[[mapping]]
namespace = "media.videoview" # map direct reads of the thingview to the same things index
index = "media.medias"


[[relate]]
namespace = "media.medias"         # when a thing changes look it up in the assoicated view by _id and index that
with-namespace = "media.videoview"
keep-src = false                   # ignore the original thing that changed and instead just use the lookup of that thing via the view

[[relate]]
namespace = "media.videos"       # when a state changes trigger a thing change event since thing is associated to a state
with-namespace = "media.medias"
src-field = "_id"                # use the _id field of the state that changed to lookup associated things
match-field = "media_data.media" # only trigger change events for the things where thing.s (match-field) = state._id (src-field).
dot-notation = true
keep-src = false

[[script]]
namespace = "media.videoview"
path = "/usr/src/app/config/relate_media_config.js"
routing = true
```

Mongodb document of the view:
```json
{
  "_id": {
    "$oid": "677cf986b383edb8aa4d534r"
  },
  "media_data": {
    "media": {
      "$oid": "677cf986b383edb8aasdsdf"
    },
    "type": "Video"
  },
  "media_values": [
    {
      "_id": {
        "$oid": "677cf986b383edasdsdfas"
      },
      "name": "Demo.mp4",
      "title": "Demo title",
      "type": "video/mp4",
      "createdAt": {
        "$numberLong": "1736243590"
      },
      "visibility": {
        "status": "NONE"
      },
      "publishedAt": {
        "$numberLong": "0"
      },
      "isPublished": false,
      "versions": [
        {
          "version": "1",
          "videoId": {
            "$oid": "677cf986b383edasdsdfas"
          }
        }
      ],
      "currentVersion": {
        "version": "1",
        "videoId": {
          "$oid": "677cf986b383edasdsdfas"
        }
      },
      "thumbnails": [
        "677cf986b383edasdsdfas-0pre.webp",
        "677cf986b383edasdsdfas-1pre.webp",
        "677cf986b383edasdsdfas-2pre.webp"
      ],
      "videoThumbnail": "677cf986b383edasdsdfas.webp",
      "format": "hls",
      "captionsGenerated": true,
      "duration": 49,
      "audioEncoded": true,
      "encoded": true,
      "aspectratio": 0.8,
      "videoOrientation": "portrait",
      "thumbnailsGenerated": true,
      "colorPalette": {
        "dominant": "#ced0dd",
        "muted": "#b8beca",
        "lightMuted": "#cdcfdc",
        "darkMuted": "#323232",
        "vibrant": "#c50708",
        "lightVibrant": "#ec0000",
        "darkVibrant": "#000000",
        "frameColor": "#f1f2f7"
      },
      "customThumbnails": [
        "677cf986b383edasdsdfas_0.webp"
      ],
      "updatedAt": {
        "$numberLong": "1736244136"
      }
    }
  ]
}
```

Correctly synced elasticsearch document for the same:
```json
{
  "_index": "media.medias",
  "_id": "677cf986b383edasdsdfas",
  "_version": 14,
  "_score": 0,
  "_source": {
    "media_data": {
      "media": "677cf986b383edasdsdfas",
      "type": "Video"
    },
    "media_values": [
      {
        "thumbnailsGenerated": true,
        "videoThumbnail": "677cf986b383edasdsdfas_0.webp",
        "visibility": {
          "status": "NONE"
        },
        "captionsGenerated": true,
        "publishedAt": 0,
        "isPublished": false,
        "videoOrientation": "portrait",
        "format": "hls",
        "title": "Demo title",
        "type": "video/mp4",
        "currentVersion": {
          "videoId": "677cf986b383edasdsdfas",
          "version": "1"
        },
        "aspectratio": 0.8,
        "duration": 49,
        "createdAt": 1736243590,
        "versions": [
          {
            "videoId": "677cf986b383edasdsdfas",
            "version": "1"
          }
        ],
        "name": "Demo.mp4",
        "_id": "677cf986b383edasdsdfas",
        "audioEncoded": true,
        "colorPalette": {
          "darkVibrant": "#000000",
          "lightMuted": "#cdcfdc",
          "vibrant": "#c50708",
          "dominant": "#ced0dd",
          "frameColor": "#f1f2f7",
          "darkMuted": "#323232",
          "muted": "#b8beca",
          "lightVibrant": "#ec0000"
        },
        "thumbnails": [
          "677cf986b383edasdsdfas-0pre.webp",
          "677cf986b383edasdsdfas-1pre.webp",
          "677cf986b383edasdsdfas-2pre.webp"
        ],
        "customThumbnails": [
          "677cf986b383edasdsdfas_0.webp"
        ],
        "encoded": true,
        "updatedAt": 1736244136
      }
    ],
    "oplog_date": "2025-01-07T10:02:20Z",
    "oplog_ts": {
      "T": 1736244140,
      "I": 163111713
    },
    "status": "NO_STATUS"
  }
}
```

This is how most of the documents are synced despite the view having media_values array populated:
```json
{
  "_index": "media.medias",
  "_id": "677cf986b383edasdsd235",
  "_version": 7457084989985784000,
  "_score": 0,
  "_source": {
    "media_data": {
      "media": "677cf986b383edasdsd234",
      "type": "Video"
    },
    "media_values": [],
    "status": "APPROVED",
    "tags": null,
    "vehicles": null,
    "oplog_date": "2025-01-07T09:28:36Z",
    "oplog_ts": {
      "T": 1736242116,
      "I": 0
    }
  },
}
```

Script file:

```js
module.exports = function(doc, ctx) {
    try {
        if (doc.hasOwnProperty("media_values") && doc.media_values && doc.hasOwnProperty('media_data') && doc.media_data) {
            // Handle Video type
            if (doc.media_data.type === "Video" && doc.media_data.media) {
                // Process title and name
                if (doc.media_values[0]) {
                    // NOTE: ALWAYS CHECK FOR BOTH `hasOwnProperty` AND THE ACTUAL VALUE
                    if (doc.media_values[0].hasOwnProperty('chapters') && doc.media_values[0].chapters) {
                        delete doc.media_values[0].chapters;
                    }
                    if (doc.media_values[0].hasOwnProperty('en') && doc.media_values[0].en) {
                        delete doc.media_values[0].en;
                    }

                    if (typeof doc.media_values[0].title === "string") {
                        doc.media_values[0].original_title = doc.media_values[0].title;
                        doc.media_values[0].title = doc.media_values[0].title.replace(/[_-]/g, "");
                    }

                    if (typeof doc.media_values[0].name === "string") {
                        doc.media_values[0].original_name = doc.media_values[0].name;
                        doc.media_values[0].name = doc.media_values[0].name.replace(/[_-]/g, "");
                    }

                    // Handle orientation
                    if (doc.media_values[0].videoOrientation) {
                        doc.media_values[0].orientation = doc.media_values[0].videoOrientation;
                        delete doc.media_values[0].videoOrientation
                    }
                }
            }

            // Handle Image type
            if (doc.media_data.type === "Image" && doc.media_data.media) {
                if (doc.media_values[0]) {

                    if (typeof doc.media_values[0].title === "string") {
                        doc.media_values[0].original_title = doc.media_values[0].title;
                        doc.media_values[0].title = doc.media_values[0].title.replace(/[_-]/g, "");
                    }

                    if (typeof doc.media_values[0].name === "string") {
                        doc.media_values[0].original_name = doc.media_values[0].name;
                        doc.media_values[0].name = doc.media_values[0].name.replace(/[_-]/g, "");
                    }
                }
            }

            doc.status = doc.hasOwnProperty("status") ? doc.status : "NO_STATUS";
            return doc;
        }

    } catch (err) {
        console.error("Error processing document:", err);
        return doc;
    }
};
```

Some of the documents have correctly embedded the `media_values` data but most of them are completely missing these values.

Any reason why this could be happening?
