### ISSUE TITLE
sync view question

### ISSUE THREAD

**Issue by llk2yq** [rwynn/monstache#742]
Here is `db.user` colletcion: (about 10000 documents)
```
{
  name: string;
  tags:Tag[]
}
```
and here is `db.user_view`: (about 30000 documents)
```
{
  name:string;
  tags:Tag; // $unwind from db.user.tags
}
```
and `monstache.toml`:
```toml
direct-read-namespaces = ["db.user_view"]
change-stream-namespaces = ["db.user"]

[[mapping]]
namespace = "db.user_view"
index = "db.user-index"

[[relate]]
namespace = "db.user"
with-namespace = "db.user_view"
keep-src = false
```

finally, there was 10000 documents in `db.user-index`, not 30000;

Is there anything missing in the config? And how to sync all 30000 documents in view to `db.user-index` ?
